## Import libraries

In [2]:
import pandas as pd
import numpy as np

## Import Files

In [5]:
brands = pd.read_csv("brands.csv")
categories = pd.read_csv("categories.csv")
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
products = pd.read_csv("products.csv")
staffs = pd.read_csv("staffs.csv")
stores = pd.read_csv("stores.csv")
stocks = pd.read_csv("stocks.csv")

## Check First 5 Rows

In [8]:
brands.head()

   brand_id   brand_name
0         1      Electra
1         2         Haro
2         3       Heller
3         4  Pure Cycles
4         5      Ritchey

In [10]:
categories.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [12]:
customers.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,Not Available,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,Not Available,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,Not Available,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,Not Available,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [14]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,shipping_status
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,Shipped
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,Shipped
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,Shipped
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,Shipped
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,Shipped

In [16]:
order_items.head()

   order_id  item_id  product_id  quantity  list_price  discount  total_sales
0         1        1          20         1      599.99      0.20     479.9920
1         1        2           8         2     1799.99      0.07    3347.9814
2         1        3          10         2     1549.00      0.05    2943.1000
3         1        4          16         2      599.99      0.05    1139.9810
4         1        5           4         1     2899.99      0.20    2319.9920

In [18]:
products.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel Ex 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [20]:
stores.head()

,store_id,store_name,phone,email,street,city,state,zip_code
0,1,Santa Cruz Bikes,(831) 476-4321,santacruz@bikes.shop,3700 Portola Drive,Santa Cruz,CA,95060
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088

In [22]:
staffs.head()

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [24]:
stocks.head()

   store_id  product_id  quantity
0         1           1        27
1         1           2         5
2         1           3         6
3         1           4        23
4         1           5        22

## Check Dataset Information

In [27]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand_id    9 non-null      int64
 1   brand_name  9 non-null      object
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes

In [29]:
categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category_id    7 non-null      int64
 1   category_name  7 non-null      object
dtypes: int64(1), object(1)
memory usage: 244.0+ bytes

In [31]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1445 non-null   int64
 1   first_name   1445 non-null   object
 2   last_name    1445 non-null   object
 3   phone        1445 non-null   object
 4   email        1445 non-null   object
 5   street       1445 non-null   object
 6   city         1445 non-null   object
 7   state        1445 non-null   object
 8   zip_code     1445 non-null   int64
dtypes: int64(2), object(7)
memory usage: 101.7+ KB

In [33]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1615 non-null   int64
 1   customer_id      1615 non-null   int64
 2   order_status     1615 non-null   int64
 3   order_date       1615 non-null   object
 4   required_date    1615 non-null   object
 5   shipped_date     1445 non-null   object
 6   store_id         1615 non-null   int64
 7   staff_id         1615 non-null   int64
 8   shipping_status  1615 non-null   object
dtypes: int64(5), object(4)
memory usage: 113.7+ KB

In [35]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     4722 non-null   int64
 1   item_id      4722 non-null   int64
 2   product_id   4722 non-null   int64
 3   quantity     4722 non-null   int64
 4   list_price   4722 non-null   float64
 5   discount     4722 non-null   float64
 6   total_sales  4722 non-null   float64
dtypes: float64(3), int64(4)
memory usage: 258.4 KB

In [37]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    321 non-null    int64
 1   product_name  321 non-null    object
 2   brand_id      321 non-null    int64
 3   category_id   321 non-null    int64
 4   model_year    321 non-null    int64
 5   list_price    321 non-null    float64
dtypes: float64(1), int64(4), object(1)
memory usage: 15.2+ KB

In [41]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    3 non-null      int64
 1   store_name  3 non-null      object
 2   phone       3 non-null      object
 3   email       3 non-null      object
 4   street      3 non-null      object
 5   city        3 non-null      object
 6   state       3 non-null      object
 7   zip_code    3 non-null      int64
dtypes: int64(2), object(6)
memory usage: 324.0+ bytes

In [43]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    939 non-null    int64
 1   product_id  939 non-null    int64
 2   quantity    939 non-null    int64
dtypes: int64(3)
memory usage: 22.1 KB

In [45]:
staffs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    10 non-null     int64
 1   first_name  10 non-null     object
 2   last_name   10 non-null     object
 3   email       10 non-null     object
 4   phone       10 non-null     object
 5   active      10 non-null     int64
 6   store_id    10 non-null     int64
 7   manager_id  9 non-null      float64
dtypes: float64(1), int64(3), object(4)
memory usage: 772.0+ bytes

## Check Missing values

In [48]:
customers.isnull().sum()

customer_id    0
first_name     0
last_name      0
phone          0
email          0
street         0
city           0
state          0
zip_code       0
dtype: int64

In [50]:
orders.isnull().sum()

order_id             0
customer_id          0
order_status         0
order_date           0
required_date        0
shipped_date       170
store_id             0
staff_id             0
shipping_status      0
dtype: int64

In [52]:
order_items.isnull().sum()

order_id       0
item_id        0
product_id     0
quantity       0
list_price     0
discount       0
total_sales    0
dtype: int64

In [54]:
products.isnull().sum()

product_id      0
product_name    0
brand_id        0
category_id     0
model_year      0
list_price      0
dtype: int64

In [56]:
staffs.isnull().sum()

staff_id      0
first_name    0
last_name     0
email         0
phone         0
active        0
store_id      0
manager_id    1
dtype: int64

In [58]:
stocks.isnull().sum()

store_id      0
product_id    0
quantity      0
dtype: int64

In [62]:
stores.isnull().sum()

store_id      0
store_name    0
phone         0
email         0
street        0
city          0
state         0
zip_code      0
dtype: int64

## Replacing null values

In [65]:
customers["phone"]=customers["phone"].fillna("Not Available")

In [67]:
customers.isnull().sum()

customer_id    0
first_name     0
last_name      0
phone          0
email          0
street         0
city           0
state          0
zip_code       0
dtype: int64

In [69]:
# Convert to datetime
orders["shipped_date"]=pd.to_datetime(orders["shipped_date"],errors="coerce")

# Create shipping status
orders["shipping_status"]=np.where(orders["shipped_date"].isnull(),"Pending","Shipped")

In [71]:
orders[["shipped_date", "shipping_status"]].tail()

     shipped_date shipping_status
1610          NaT         Pending
1611          NaT         Pending
1612          NaT         Pending
1613          NaT         Pending
1614          NaT         Pending

## Check and Remove Duplicates

In [74]:
brands.duplicated().sum()

0

In [76]:
brands['brand_id'].duplicated().sum()

0

In [78]:
categories.duplicated().sum()

0

In [80]:
categories['category_id'].duplicated().sum()

0

In [82]:
customers.duplicated().sum()

0

In [84]:
customers['customer_id'].duplicated().sum()

0

In [86]:
orders.duplicated().sum()

0

In [88]:
orders['order_id'].duplicated().sum()

0

In [90]:
order_items.duplicated().sum()

0

In [94]:
products['product_id'].duplicated().sum()

0

In [96]:
products.duplicated().sum()

0

In [98]:
staffs.duplicated().sum()

0

In [100]:
staffs['staff_id'].duplicated().sum()

0

In [102]:
stores['store_id'].duplicated().sum()

0

In [104]:
stores.duplicated().sum()

0

In [106]:
stocks.duplicated().sum()

0

## Normalaize the data

In [109]:
brands["brand_name"]=brands["brand_name"].str.strip()

In [111]:
categories["category_name"]=categories["category_name"].str.strip()

In [113]:
products["product_name"]=products["product_name"].str.strip()

In [115]:
stores["store_name"]=stores["store_name"].str.strip()

## Check Unique values

In [118]:
brands["brand_name"].unique()

array(['Electra', 'Haro', 'Heller', 'Pure Cycles', 'Ritchey', 'Strider',
       'Sun Bicycles', 'Surly', 'Trek'], dtype=object)

In [120]:
categories["category_name"].unique()

array(['Children Bicycles', 'Comfort Bicycles', 'Cruisers Bicycles',
       'Cyclocross Bicycles', 'Electric Bikes', 'Mountain Bikes',
       'Road Bikes'], dtype=object)

In [122]:
products["product_name"]=products["product_name"].str.title()

## Convert datatype

In [125]:
orders["order_date"]=pd.to_datetime(orders["order_date"])
orders["required_date"]=pd.to_datetime(orders["required_date"])

In [127]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1615 non-null   int64
 1   customer_id      1615 non-null   int64
 2   order_status     1615 non-null   int64
 3   order_date       1615 non-null   datetime64[ns]
 4   required_date    1615 non-null   datetime64[ns]
 5   shipped_date     1445 non-null   datetime64[ns]
 6   store_id         1615 non-null   int64
 7   staff_id         1615 non-null   int64
 8   shipping_status  1615 non-null   object
dtypes: datetime64[ns](3), int64(5), object(1)
memory usage: 113.7+ KB

In [129]:
staffs["manager_id"]=staffs["manager_id"].astype("Int64")

In [131]:
staffs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    10 non-null     int64
 1   first_name  10 non-null     object
 2   last_name   10 non-null     object
 3   email       10 non-null     object
 4   phone       10 non-null     object
 5   active      10 non-null     int64
 6   store_id    10 non-null     int64
 7   manager_id  9 non-null      Int64
dtypes: Int64(1), int64(3), object(4)
memory usage: 782.0+ bytes

## Create a new column

In [136]:
order_items["total_sales"]=( order_items["quantity"]*order_items["list_price"]*(1 - order_items["discount"]))

## Install PostgreSQL

In [139]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\acer\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\acer\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

## Connect and load into PostgreSQL

In [147]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus
username='postgres'
password=quote_plus('Gopi12@')
host='localhost'
port='5432'
database='RetailDB'
engine=create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

In [149]:
brands.to_sql(
    'brands',
    engine,
    if_exists='replace',
    index=False
)

9

In [151]:
categories.to_sql(
    'categories',
    engine,
    if_exists='replace',
    index=False
)

7

In [153]:
customers.to_sql(
    'customers',
    engine,
    if_exists='replace',
    index=False
)

445

In [155]:
orders.to_sql(
    'orders',
    engine,
    if_exists='replace',
    index=False
)

615

In [157]:
order_items.to_sql(
    'order_items',
    engine,
    if_exists='replace',
    index=False
)

722

In [159]:
products.to_sql(
    'products',
    engine,
    if_exists='replace',
    index=False
)

321

In [161]:
staffs.to_sql(
    'staffs',
    engine,
    if_exists='replace',
    index=False
)

10

In [163]:
stores.to_sql(
    'stores',
    engine,
    if_exists='replace',
    index=False
)

3

In [165]:
stocks.to_sql(
    'stocks',
    engine,
    if_exists='replace',
    index=False
)

939